version: "3"

services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - ~/Docker/sonarqube/conf:/opt/sonarqube/conf
      - ~/Docker/sonarqube/data:/opt/sonarqube/data
      - ~/Docker/sonarqube/extensions:/opt/sonarqube/extensions
      - ~/Docker/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    container_name: sonarqube_postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ~/Docker/sonarqube/postgresql/postgresql:/var/lib/postgresql
        # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    networks:
      - sonarnet
      - dockernet
    ports:
      - "8080:80"
      - "5000:5000"
    environment:
      - JENKINS_HOME=/var/jenkins_home
    volumes:
      - ~/Docker/jenkins:/var/jenkins_home

networks:
  sonarnet:
    driver: bridge
  dockernet:
    external: true

volumes:
  postgresql_data:
